config/routes.rb
Rails.application.routes.draw do
  root 'images#index'
  resources :images do
    member do
      get "like", to: "images#upvote"
      get "dislike", to: "images#downvote"
    end
    collection do
      get 'search'
    end
  end
  devise_for :users
  resources :users, only: [:show]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/image.rb
class Image < ApplicationRecord
  def self.search(search)
    where("title ILIKE ?", "%#{search}%")
  end
  acts_as_votable
  belongs_to :user
  validates_presence_of :image, :title
  has_attached_file :image, styles: { medium: "1024x1540>", small:"1024x768>" }
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :validatable, password_length: 8..30
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :images
  has_attached_file :avatar, styles: { medium: "128x128#", small: "32x32#" }
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/
  validates :email, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name])
    devise_parameter_sanitizer.permit(:sign_up, keys: [:last_name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:last_name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:avatar])
    devise_parameter_sanitizer.permit(:account_update, keys: [:city])
    devise_parameter_sanitizer.permit(:account_update, keys: [:state])
    devise_parameter_sanitizer.permit(:account_update, keys: [:about_me])
  end
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
  before_action :set_image, only: [:show, :edit, :update, :destroy, :upvote, :downvote]
  before_action :authenticate_user!, except: [:index, :show, :search]

  def index
    @images = Image.all
  end

  def search
    if params[:search]
      @images = Image.search(params[:search]).order("created_at DESC")
    else
      @images = Image.all.order("created_at DESC")
    end
  end

  def show
  end

  def new
    @image = Image.new
  end

  def create
    @image = Image.new(image_params)
    if @image.save
      redirect_to root_path
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @image.update(image_params)
      redirect_to image_path
    else
      render :edit
    end
  end

  def destroy
    if @image.destroy
      redirect_to root_path
    end
  end

  def upvote
    @image.upvote_by current_user

    respond_to do |format|
      format.html { redirect_to :back }
      format.json { render json: { count: @image.get_upvotes.size } }
    end
  end

  def downvote
    @image.downvote_by current_user

    respond_to do |format|
      format.html { redirect_to :back }
      format.json { render json: { count: @image.get_downvotes.size } }
    end
  end

  private

  def set_image
    @image = Image.find(params[:id])
  end

  def image_params
    params.require(:image).permit(:title, :description, :image, :user_id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/devise_helper.rb
module DeviseHelper
  def devise_error_messages!
    return '' if resource.errors.empty?

    messages = resource.errors.full_messages.map { |msg| content_tag(:p, msg) }.join
    html = <<-HTML
    <div class="alert alert-danger"> <button type="button"
    class="close" data-dismiss="alert">×</button>
      #{messages}
    </div>
    HTML

    html.html_safe
  end
end

app/helpers/images_helper.rb
module ImagesHelper
  def full_name1
    @image.user.first_name + ' ' + @image.user.last_name
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def full_name
    @user.first_name + ' ' + @user.last_name
  end
  
  def location
    @user.city + ', ' + @user.state
  end
end

app/views/images/edit.html.erb
<div class="form-center">
  <h1>Change It to your liking</h1>
  <%= form_for @image, html: { multipart: true } do |f| %>
    <% if @image.errors.any? %>
      <div class="alert alert-danger">
        <a href="#" data-dismiss="alert" class="close">×</a>
        <% @image.errors.full_messages.each do |message| %>
            <p><%= message %></p>
        <% end %>
      </div>
    <% end %>
    <div>
      <%= f.label :title %><br />
      <%= f.text_field :title, class: 'input' %>
    </div>
    <div>
      <%= f.label :description %><br />
      <%= f.text_area :description, class: 'textarea' %>
    </div>
    <div>
      <%= f.submit "Submit", class: "submit" %>
    </div>
  <% end %>
  <p class="back"><%= link_to "Back", :back %></p>
</div>

app/views/images/index.html.erb
<div class="jumbotron application-jumbotron disappear1">
  <div class="container">
    <h1>Add Your Favorite Design's and Photo's</h1>
    <p>Here at Backdrop you can add any photo or design you want, whether you want them to be rated or just for other people to see. There's no judgement here so add whatever you want, as long as it's apropriate.</p>
    <p><%= link_to "Add a photo", new_image_path, class: "btn btn-primary btn-lg" %></p>
  </div>
</div>

<% @images.order("id DESC").limit(50).each do |image| %>
    <%= link_to (image_tag image.image.url(:small), class: 'image'), image %>
    <div class="index-margin">
      <%= link_to like_image_path(image), method: :get, class: "upvote-image data hover", data: {imageId: "#{image.id}"} do %>
        <i class="glyphicon glyphicon-thumbs-up"><%= pluralize(image.get_upvotes.size, "Like") %></i>
      <% end %>
      <%= link_to dislike_image_path(image), method: :get, class: "downvote-image data hover", data: {imageId: "#{image.id}"} do %>
        <i class="glyphicon glyphicon-thumbs-down"><%= pluralize(image.get_downvotes.size, "Dislike") %></i>
      <% end %>
      <div class="middle-index">
        <% if !image.user.avatar_file_name.nil? %>
          <%= link_to image.user, class: "hover" do %>
            <%= image_tag image.user.avatar.url(:small), class: "avatar" %>
          <% end %>
        <% else %>
          <%= link_to image.user, class: "hover" do %>
            <img class="avatar" src="<%= asset_path("anonymous.jpg") %>" />
          <% end %>
        <% end %>
        <% if !image.user.first_name.empty? || !image.user.last_name.empty? %>
            <%= link_to image.user.first_name + ' ' + image.user.last_name, image.user, class: "disappear" %>
        <% else %>
            <%= link_to "Anonymous Author", image.user, class: "disappear" %>
        <% end %>
      </div>
      <p class="posted">Posted <%= time_ago_in_words(image.created_at) %> ago</p>
    </div>
<% end %>

app/views/images/new.html.erb
<div class="form-center">
  <h1>Add Some Photos</h1>
  <%= form_for @image, html: { multipart: true } do |f| %>
    <% if @image.errors.any? %>
      <div class="alert alert-danger">
        <a href="#" data-dismiss="alert" class="close">×</a>
        <% @image.errors.full_messages.each do |message| %>
            <p><%= message %></p>
        <% end %>
      </div>
    <% end %>
    <div>
      <%= f.label :title %><br />
      <%= f.text_field :title, class: 'input' %>
    </div>
    <div>
      <%= f.label :image %><br />
      <%= f.file_field :image %>
    </div>
    <div>
      <%= f.label :description %><br />
      <%= f.text_area :description, class: 'textarea' %>
    </div>
    <%= f.hidden_field :user_id, value: current_user.id %>
    <div>
      <%= f.submit "Submit", class: "submit" %>
    </div>
  <% end %>
</div>

app/views/images/search.html.erb
<% if @images.blank? %>
  <div class="alert alert-info">
    <button type="button" class="close" data-dismiss="alert">×</button>
    <p>There are no images with the title <%= params[:search] %>.</p>
  </div>
<% end %>

<% @images.each do |image| %>
    <%= link_to (image_tag image.image.url(:small), class: 'image'), image %>
    <div class="index-margin">
        <%= link_to like_image_path(image), method: :get, class: "data hover" do %>
          <i class="glyphicon glyphicon-thumbs-up"><%= pluralize(image.get_upvotes.size, "Like") %></i>
        <% end %>
        <%= link_to dislike_image_path(image), method: :get, class: "data hover" do %>
          <i class="glyphicon glyphicon-thumbs-down"><%= pluralize(image.get_downvotes.size, "Dislike") %></i>
        <% end %>
        <div class="middle-index">
            <% if !image.user.avatar_file_name.nil? %>
              <%= link_to image.user, class: "hover" do %>
                <%= image_tag image.user.avatar.url(:small), class: "avatar" %>
              <% end %>
            <% else %>
              <%= link_to image.user, class: "hover" do %>
                <img class="avatar" src="<%= asset_path("anonymous.jpg") %>" />
              <% end %>
            <% end %>
            <% if !image.user.first_name.empty? || !image.user.last_name.empty? %>
              <%= link_to image.user.first_name + ' ' + image.user.last_name, image.user, class: "disappear" %>
            <% else %>
              <%= link_to "Anonymous Author", image.user, class: "disappear" %>
            <% end %>
        </div>
        <p class="posted">Posted <%= time_ago_in_words(image.created_at) %> ago</p>
    </div>
<% end %>

app/views/images/show.html.erb
<h1 class="show-page-title disappear1 get-smaller"><%= @image.title %></h1>
<%= image_tag @image.image.url(:small), class: "image" %>
<div class="index-margin">
  <%= link_to like_image_path(@image), method: :get, class: "data hover" do %>
    <i class="glyphicon glyphicon-thumbs-up"><%= pluralize(@image.get_upvotes.size, "Like") %></i>
  <% end %>
  <%= link_to dislike_image_path(@image), method: :get, class: "data hover" do %>
    <i class="glyphicon glyphicon-thumbs-down"><%= pluralize(@image.get_downvotes.size, "Dislike") %></i>
  <% end %>
  <div class="middle-index">
    <% if !@image.user.avatar_file_name.nil? %>
      <%= link_to @image.user, class: "hover" do %>
        <%= image_tag @image.user.avatar.url(:small), class: "avatar" %>
      <% end %>
    <% else %>
      <%= link_to @image.user, class: "hover" do %>
        <img class="avatar" src="<%= asset_path("anonymous.jpg") %>" />
      <% end %>
    <% end %>
    <% if !@image.user.first_name.empty? || !@image.user.last_name.empty? %>
      <%= link_to full_name1, @image.user, class: "disappear" %>
    <% else %>
      <%= link_to "Anonymous Author", @image.user, class: "disappear" %>
    <% end %>
  </div>
  <p class="posted">Posted <%= time_ago_in_words(@image.created_at) %> ago</p>
</div>
<div class="jumbotron application-jumbotron margin-b disappear1">
  <div class="container">
    <% if !@image.description.empty? %>
      <h1 class="get-smaller smaller-thoughts">Author's Thoughts:</h1>
      <p class="get-small"><%= @image.description %></p>
    <% else %>
      <h1 class="get-smaller smaller-thoughts">Author's Thoughts:</h1>
      <p class="get-small">No description</p>
    <% end %>
  </div>
</div>

<% if user_signed_in? %>
  <% if @image.user_id == current_user.id %>
    <p class="edit-delete"><%= link_to 'Edit', edit_image_path %> | <%= link_to "Delete", image_path, method: :delete, data: { confirm: "Are you sure?" } %></p>
  <% end %>
<% end %>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <div class="container">
    <p class="text-muted">&copy; 2017 <%= link_to "Backdrop", root_path %></p>
  </div>
</footer>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to image_tag(asset_path("camera.png"), class: "navbar-img"), root_path, class: "navbar-brand" %>
    </div>

    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
          <li><%= link_to "Home", root_path %></li>
          <li><%= link_to "Add a photo", new_image_path %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Profile <span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><%= link_to "Account", current_user %></li>
              <li><%= link_to "Settings", edit_user_registration_path %></li>
              <li><%= link_to "Logout", destroy_user_session_path, data: { confirm: "Are you sure?" }, method: :delete, class: "active" %></li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Home", root_path %></li>
          <li><%= link_to "Sign Up", new_user_registration_path%></li>
          <li><%= link_to "Login", new_user_session_path %></li>
        <% end %>
      </ul>
      <%= form_tag search_images_path, method: :get, class: "navbar-form navbar-left", id:'search-form', role: "search" do %>
        <div class="row">
          <div class="col-sm-9 col-lg-6">
            <div class="input-group">
              <span class="input-group-btn">
                <%= button_tag(type: 'submit', :name => nil, class: "btn btn-default") do %>
                 <span class="glyphicon glyphicon-search"></span>
                <% end %>
              </span>
              <div class="form-group">
                <%= text_field_tag :search, params[:search], placeholder: 'Search...', class: "form-control" %>
              </div>
            </div>
          </div>
        </div>
    <% end %>
  </div>
</nav>

app/views/layouts/_messages.html.erb
<% flash.each do |key, value| %>
  <div class="alert alert-info">
    <a href="#" data-dismiss="alert" class="close">×</a>
    <p><%= value %></p>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Backdrop</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet", href="http://cdnjs.cloudflare.com/ajax/libs/normalize/3.0.1/normalize.min.css" />
    <%= favicon_link_tag 'favicon.ico' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <div class="container main">
      <%= render 'layouts/messages' %>
      <%= yield %>
    </div>
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/users/show.html.erb
<% if !@user.avatar_file_name.nil? %>
  <p class="center"><%= image_tag @user.avatar.url(:medium), class: "avatar1" %></p>
<% else %>
  <p class="center"><img class="avatar1" src="<%= asset_path("anonymous.jpg") %>" /></p>
<% end %>


<% if !@user.first_name.empty? || !@user.last_name.empty? %>
  <p class="name">
    <%= full_name %>
  </p>
<% else %>
  <p class="name">
    Anonymous
  </p>
<% end %>
<div class="user-show-menu">
  <% if !@user.city.to_s.empty? && !@user.state.to_s.empty? %>
    <p class="user-location">
      Location: <%= location %>
    </p>
  <% elsif !@user.city.to_s.empty? %>
    <p class="user-location">
      City: <%= @user.city %>
    </p>
  <% elsif !@user.state.to_s.empty? %>
    <p class="user-location">
      Province/State: <%= @user.state %>
    </p>
  <% else %>
    <p class="user-location">
      Not from this world!
    </p>
  <% end %>
</div>

<div class="jumbotron user-jumbotron">
  <div class="container">
    <p><%= @user.about_me %></p>
  </div>
</div>

<% @user.images.order("id DESC").each do |image| %>
  <%= link_to (image_tag image.image.url(:medium), class: "image1"), image %>
  <div class="index-margin">
    <%= link_to like_image_path(image), method: :get, class: "data hover" do %>
      <i class="glyphicon glyphicon-thumbs-up"><%= pluralize(image.get_upvotes.size, "Like") %></i>
    <% end %>
    <%= link_to dislike_image_path(image), method: :get, class: "data hover" do %>
      <i class="glyphicon glyphicon-thumbs-down"><%= pluralize(image.get_downvotes.size, "Dislike") %></i>
    <% end %>
    <div class="middle-index">
      <% if !image.user.avatar_file_name.nil? %>
        <%= link_to image.user, class: "hover" do %>
          <%= image_tag image.user.avatar.url(:small), class: "avatar" %>
        <% end %>
      <% else %>
        <%= link_to image.user, class: "hover" do %>
          <img class="avatar" src="<%= asset_path("anonymous.jpg") %>" />
        <% end %>
      <% end %>
      <% if !image.user.first_name.empty? || !image.user.last_name.empty? %>
        <%= link_to full_name, image.user, class: "disappear" %>
      <% else %>
        <%= link_to "Anonymous Author", image.user, class: "disappear" %>
      <% end %>
    </div>
    <p class="posted">Posted <%= time_ago_in_words(image.created_at) %> ago</p>
  </div>
<% end %>